/* 
 * The One Api
 *
 * API for the-one-api.dev
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TheOneApi.Api;
using TheOneApi.Model;
using TheOneApi.Client;
using System.Reflection;

namespace TheOneApi.Test
{
    /// <summary>
    ///  Class for testing Docs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocsTests
    {
        private Docs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Docs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Docs
        /// </summary>
        [Test]
        public void DocsInstanceTest()
        {
            Assert.IsInstanceOf<Docs> (instance, "instance is a Docs");
        }

        /// <summary>
        /// Test the property 'AcademyAwardNominations'
        /// </summary>
        [Test]
        public void AcademyAwardNominationsTest()
        {
            // TODO: unit test for the property 'AcademyAwardNominations'
        }
        /// <summary>
        /// Test the property 'AcademyAwardWins'
        /// </summary>
        [Test]
        public void AcademyAwardWinsTest()
        {
            // TODO: unit test for the property 'AcademyAwardWins'
        }
        /// <summary>
        /// Test the property 'BoxOfficeRevenueInMillions'
        /// </summary>
        [Test]
        public void BoxOfficeRevenueInMillionsTest()
        {
            // TODO: unit test for the property 'BoxOfficeRevenueInMillions'
        }
        /// <summary>
        /// Test the property 'BudgetInMillions'
        /// </summary>
        [Test]
        public void BudgetInMillionsTest()
        {
            // TODO: unit test for the property 'BudgetInMillions'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RottenTomatoesScore'
        /// </summary>
        [Test]
        public void RottenTomatoesScoreTest()
        {
            // TODO: unit test for the property 'RottenTomatoesScore'
        }
        /// <summary>
        /// Test the property 'RuntimeInMinutes'
        /// </summary>
        [Test]
        public void RuntimeInMinutesTest()
        {
            // TODO: unit test for the property 'RuntimeInMinutes'
        }

    }

}
